
CREATE OR REPLACE TABLE PROD.GIT_TEST.ORDERS_ENTITY AS 

SELECT
    so.ORDER_ID
  , so.CUSTOMER_ID
  , cm.PROFILE_ID
  , so.CREATED_AT
  , so.UPDATED_AT
  , so.CLOSED_AT
  , so.PROCESSED_AT
  , so.CANCELLED_AT
  , so.SUBTOTAL_LINE_ITEMS_QUANTITY
  , so.CURRENT_SUBTOTAL_LINE_ITEMS_QUANTITY
  , so.CURRENCY_CODE
  , so.CUSTOMER_PAID
  , so.ITEMS_PRICE
  , so.NET_PAYMENT
  , so.TOTAL_REFUNDED
  , so.TOTAL_TAX
  , so.NET_REVENUE
  , so.TOTAL_SHIPPING_PRICE
  , so.TOTAL_DISCOUNTS
  , so.DISCOUNT_CODE
  , so.NAME
  , so.COUNTRY_CODE
  , so.CUSTOMER_ACCEPTS_MARKETING
  , so.PAYMENT_PORTAL
  , so.REFERRER_DISPLAY_TEXT
  , so._KLEENE_METADATA_ID
  , so._KLEENE_EXTRACT_DATE
FROM
  PROD.SHOPIFY_SUBENTITY.SHOPIFY_ORDERS_SUBENTITY so
LEFT JOIN 
(select *
from PROD.MASTERING.CUSTOMER_MASTERING
qualify row_number() over (partition by customer_id order by last_interaction desc ) = 1
) cm 
  on so.customer_id = cm.customer_id

;